### ISSUE TITLE
Swift 4.2 not working with Parrot Mambo

### ISSUE THREAD

**Issue by MeesterZee** [Parrot-Developers/Drone-Swift-Playgrounds#2] opened 2019-05-20 18:22 UTC
The Parrot Education Swift 4.2 playground is unable to pair correctly with the Parrot Mambo drone and appears broken after failing to pair correctly. Running latest versions of iOS (12.3) and Swift Playgrounds app are installed.

**Comment by JeromeBouvard** [comment] 2019-06-10 17:39
Thanks for the feedback. Could you please activate the Swift Playground debug mode on your iPad and post a log? We are unable to reproduce the issue on our own iPad / Mambo.
Thanks

iPad General Settings->Playgrounds-> Authoring Debug Mode
<img width="1112" alt="IMG_548AB2C18FBC-1" src="https://user-images.githubusercontent.com/1897662/59214489-04840300-8b6c-11e9-98fe-58ac89d76da1.png">

**Comment by alfredhart** [comment] 2019-06-10 17:40
We are having the same issue.  Works on iPad Pro but not with any other iPad generation we have tried.  Anyone have a suggestion on a fix?

**Comment by MeesterZee** [comment] 2019-06-10 18:02
Hi Jerome, I have activated debug mode, but I am not sure how to retrieve the logged data. Attached is a screenshot of the broken swift module after attempting to connect with the drone.


--Nick

________________________________

**Comment by MeesterZee** [comment] 2019-06-10 18:04
Hi Jerome, I have activated debug mode, but I am not sure how to retrieve the logged data. Attached is a screenshot of the broken swift module after attempting to connect with the drone.
![IMG_0042 1](https://user-images.githubusercontent.com/50843764/59216002-89245080-8b6f-11e9-978e-4e04238490ac.PNG)

**Comment by JeromeBouvard** [comment] 2019-06-10 18:09
It should display a crash message? 
can you reset the book and try from scratch?
thanks

**Comment by MeesterZee** [comment] 2019-06-10 18:13
I deleted the book and downloaded again. I tap connect and the book shows the proper graphics and sees the drone in the connection list. When I select the drone from the list, a connection attempt is made, and the upper graphical portion of the book crashes. No crash message displays.

**Comment by MeesterZee** [comment] 2019-06-10 18:14
I started an additional discussion thread here: https://discussions.apple.com/thread/250377034

**Comment by alfredhart** [comment] 2019-06-10 18:25
I'm seeing exactly the same behavior as MeesterZee.

**Comment by JeromeBouvard** [comment] 2019-06-10 18:42
Can you list your ipad model ?

**Comment by MeesterZee** [comment] 2019-06-10 18:58
iPad 6th Gen MR7F2LL/A. Other iPads (same model) that are running previous versions of the swift playgrounds book behave correctly.

**Comment by alfredhart** [comment] 2019-06-10 19:10
I have tried on several iPad mini 2nd gen A1489 and an iPad Air but I don't currently have the model of the Air handy.

**Comment by JeromeBouvard** [comment] 2019-06-10 20:49
Could you guys test this book ?
https://www.dropbox.com/s/4kqprnfqrw0c6u5/Parrot%20Education.playgroundbook.zip?dl=0

**Comment by alfredhart** [comment] 2019-06-10 21:25
That book is working with the iPad mini 2nd I have in my office now.  I'm collecting the rest of our 20 iPads to load this book tonight so that we can use tomorrow for our program.  Do you know how long before the Swift Playground listing can be updated?

**Comment by MeesterZee** [comment] 2019-06-10 22:01
I'm not sure how to load this book since all our iPads are managed through an MDM.

**Comment by alfredhart** [comment] 2019-06-10 22:52
If Airdrop isn’t restricted, I was able to airdrop the file to the iPad
after turning Airdrop on.
Al

**Comment by JeromeBouvard** [comment] 2019-06-10 22:58
Yes, Airdrop them from a Mac or from another iPad.
This book works for me on the iPad mini 4 I have, it was not working before.
Hopefully, it is a quick fix, I will work on updating the stream asap.

**Comment by MeesterZee** [comment] 2019-06-11 14:30
Working great on all our iPad 6th Gen!

**Comment by JeromeBouvard** [comment] 2019-06-11 14:33
good to hear :)

**Comment by gbutler1974** [comment] 2019-06-18 16:32
Totla noob here - I have the same problem - I don't know what anyone means by this book? How do i get it on my ipad? I see a dropbox folder and contents, but what do i do with it? Thanks in advance.

**Comment by JeromeBouvard** [comment] 2019-06-20 16:39
Fixed on v1.3

**Closed as completed by JeromeBouvard** 2019-06-20 16:39 UTC

**Comment by gbutler1974** [comment] 2019-06-20 17:08
Jerome, I'm not sure what you mean. I updated the drone firmware yesterday when it arrived and I was getting this problem with no option to connect to the drone from swift playground after it has crashed the first time. Is there an update since yesterday? I appreciate any help.

**Comment by JeromeBouvard** [comment] 2019-06-25 18:56
You need to update the Swift Playgrounds Parrot feed.
Unsubscribe and subscribe again, you will see the book v1.3
![swift](https://user-images.githubusercontent.com/1897662/60125233-3be3d980-9740-11e9-8498-ac34b5cb830c.JPG)

**Comment by sgvkids** [comment] 2019-07-19 17:40
Jerome,
I have the 6th generation iPad and Parrot Education doesn’t pair with the Mambo drone.
I don’t understand how to install the book.  Can you pls give the instructions to fix this problem?

**Comment by georgmierau** [comment] 2023-01-27 07:49
Is there a way for this playground to work under iPadOS 16.x on an M1 and/or a regular iPad?
I'm using Playbook version 1.5.
